services:
  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
    command: >
      /cloud-sql-proxy
      ${CLOUD_SQL_INSTANCE}
      --port=3306
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/service-account.json
    volumes:
      - ./secrets:/secrets:ro
    restart: always

  backend:
    image: course_backend
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - cloudsql-proxy
